name: Spark ETL CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Set dataset path environment variable
      run: echo "DATASET_PATH=${{ secrets.DATASET_PATH }}" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pyspark

    - name: Run the script
      run: spark-submit make_etl.py
      working-directory: ${{ github.workspace }}
